### ISSUE TITLE
OMEMO bundles not being published for devicelist

### ISSUE THREAD

**Issue by chrisballinger** [zom/Zom-Android-XMPP#226] opened 2017-04-21 18:22 UTC
When I was attempting to chat with Carrie, her Android client was advertising a devicelist, but when I ask for the OMEMO bundle for the deviceId she's advertising, there is nothing there.. so session initiation fails. Better validation should be done to ensure there's always a fresh bundle published for the client's deviceId, and that the advertised devicelist is accurate.

**Comment by n8fr8** [comment] 2017-04-21 20:21
@vanitasvitae any thoughts on this? Is there something we need to do in order to ensure fresh bundles are published?

**Comment by vanitasvitae** [comment] 2017-04-21 21:14
This issue is caused by Prosody not persisting published pubsub items over restarting the server. That means, that after a restart all pubsub items are gone.

Additionally there was a bug in smack-omemo that was fixed a few days ago, which prevented smack-omemo from publishing the device bundle when the device id appeared on the device list. This has been fixed with https://github.com/vanitasvitae/smack-omemo/commit/9c97233d0ea13d8a2b315e5bd9af0faeaaa3b8f0 so now we publish our bundle on every start. I suppose, Zom is not targeting the latest commit at the moment? There have been quite a lot of improvements.

Btw: We hope to get smack-omemo merged into smack within the next days :tada:

**Comment by vanitasvitae** [comment] 2017-04-22 18:48
I discovered some more bugs with help of @mimi89999. There were some more issues with prosody behaving different than ejabberd (which I mainly test with). We got it working now. Its really time for integration tests...

**Comment by n8fr8** [comment] 2017-05-05 15:36
This if fixed now.

**Closed as completed by n8fr8** 2017-05-05 15:36 UTC
