### ISSUE TITLE
Photos not received unless chat was open

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#222] opened 2017-04-20 01:06 UTC
The user had the app open to the conversations view. A friend was sending photos, but they didn’t show up until the user opened the chat view with the friend.

version 15.1.0-alpha-1

**Comment by n8fr8** [comment] 2017-05-05 15:39
I can't reproduce this

**Comment by n8fr8** [comment] 2017-08-09 20:26
Is def fixed with new file sharing, etc.

**Closed as completed by n8fr8** 2017-08-09 20:26 UTC
Labels: bug
