### ISSUE TITLE
Contacts didn't get a new key for friend with fresh install

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#403] opened 2018-01-22 16:13 UTC
For my friends, my key didn't auto update after I got a fresh install. In my friends list, everyone is listed with 'sorry you are blocked by the user'.

If I verify a contact, we are both able to chat. The friends I've verified are listed in my friends list and do not say that I'm blocked by them.

Samsung Galaxy
Build: 15.3.2 beta 2
OS: 7.0

**Comment by n8fr8** [comment] 2018-02-05 18:16
I overhauled the login/roster/friends loading code

**Comment by tiffrobo** [comment] 2018-02-06 19:56
I uninstalled the app and reinstalled the app. Logging into a previous account (created earlier today). I also, tested by unistalling and re-logging into an old account (from a few months ago) and saw the same issues. 
Friends list shows multiples of friends. None with 'sorry you are blocked by the user.'

If I was a friend with them prior to the new install then there are 3 variations of the contact listed: 

1. Shows pending approval 
2. Shows their JID. 
3. Shows their JID (exactly as the one above it). 

![screenshot_20180206-131222](https://user-images.githubusercontent.com/30634981/35880773-6abf19f6-0b44-11e8-9d05-b8a9cb7fe96b.png)

**Same QR codes**
![screenshot_20180206-131214](https://user-images.githubusercontent.com/30634981/35880801-7bc8dc1e-0b44-11e8-89ba-c7bb2e77a6c4.png)
![screenshot_20180206-131206](https://user-images.githubusercontent.com/30634981/35880803-7e093168-0b44-11e8-8c0e-ecf5abbdcf33.png)


- Chats sent to any of the 'contacts' listed goes through (is received). 
- On the sender side sent chat history only appear in 1 'contact' and 2 'contact'. 

- 3 'contact' chat history appears blank, but you can type and send a message from this 'contact' which is received and shows in 2 'contact' chat history.

![screenshot_20180206-131147](https://user-images.githubusercontent.com/30634981/35880827-8f469790-0b44-11e8-8336-5d9db156c9b4.png)

- The receiver sees no new friend request or apparent issue. 
Yet, their sent messages are not received. 

- If they verify the contact they can send messages which are then received. 
- The initial issue remains for the contact with the fresh install.

![img_774b9fc3b9d3-1](https://user-images.githubusercontent.com/30634981/35879859-ea5e38a2-0b41-11e8-9d53-0dd6ff71888b.jpeg)






- Also, any new friend is auto-duplicated. Tapping 'accept' did not resolve the issue. 

![screenshot_20180206-133335](https://user-images.githubusercontent.com/30634981/35880678-322cfd60-0b44-11e8-9c60-52238b9189fd.png)
![screenshot_20180206-133556](https://user-images.githubusercontent.com/30634981/35880673-2d8f3124-0b44-11e8-8e7e-c3c9117ebc8e.png)



- I retested a new install and re-logging into a very, very old account (created a few months ago) and saw no problems.  


Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

App version: 15.4.0-beta-1

**Comment by tiffrobo** [comment] 2018-02-06 21:12
Update: 
'My account' view shows two identical accounts. Same QRs. 
Turning one to offline and one online does not affect the above issue. 

![screenshot_20180206-143836](https://user-images.githubusercontent.com/30634981/35884350-0b26c2e4-0b50-11e8-88ec-890cbd54b501.png)

![screenshot_20180206-143938](https://user-images.githubusercontent.com/30634981/35884337-fdf28c0c-0b4f-11e8-8803-5382ab34eb0d.png)
![screenshot_20180206-143915](https://user-images.githubusercontent.com/30634981/35884343-023c16a2-0b50-11e8-82f2-72b0e9860a74.png)

**Comment by n8fr8** [comment] 2018-02-07 15:53
I've tried to disable the ability to accidentally create duplicate accounts during onboarding. I think you somehow tapped twice and that cause the dup accounts. Most of the other issues reported here were caused by the dup accounts and contacts.

**Comment by tiffrobo** [comment] 2018-02-07 16:21
- Closing the ticket. No longer seeing the original issue in my friend's list, that everyone is listed with 'sorry you are blocked by the user'.

- Also, the duplicate accounts may have been triggered during onboarding due to tapping the sign in button twice. During retesting, we didn't see the duplicate accounts anymore (tapping once and tapping twice). 
- Nothing funky was produced with the friend's list.

**Closed as completed** 2018-02-07 17:05 UTC
Labels: bug, high, FOR REVIEW
